# Sources:
# Attached to gear
# Place
# Place with characters conditions 
# Gear characteristics with character conditions
# Scales by level: F(x) = x*(base/2) + (base/2)*x^1.5
# 
# 

# 
# Remove <name> stackable. [returns amount removed]
# <amount> = X + Y * returned var
# Take <amount> <type> damage.
# Add <amount> <name> stackable.
# 
# 
# 
# 
# 
# 
# 
# 


